# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:

  build:
    docker:
      - image: circleci/node:8.9.1
    steps:
      ### CHECKOUT
      # circleCI clones the code into ~/project
      - checkout
      
      ### BUILD
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "~/project/app/server/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install-dependencies
          command: cd ~/project/app/server && npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "~/project/app/server/package.json" }}
      
      ### TEST
      - run: mkdir ~/junit
      - run:
          command: cd ~/project/app/server 
            && node_modules/mocha/bin/_mocha test --reporter mocha-junit-reporter --exit
            && if [[ -e test-results.xml ]]; then cp test-results.xml $CIRCLE_TEST_REPORTS/test-results.xml; fi
          # environment:
          #   MOCHA_FILE: ~/junit/test-results.xml
          when: always
      - store_test_results:
          path: $CIRCLE_TEST_REPORTS/test-results.xml
      - store_artifacts:
          path: $CIRCLE_TEST_REPORTS/test-results.xml
          destination: test-results.xml