# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:

  build:
    docker:
      - image: circleci/node:8.9.1
    steps:
      ### CHECKOUT
      - checkout
      
      ### BUILD
      - run: cd kinesis-stream-reader/app/server
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "package.json" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-
      - run:
          name: install-dependencies
          command: npm install
      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v1-dependencies-{{ checksum "package.json" }}
      
      ### TEST
      - run: mkdir ~/junit
      - run:
          command: mocha test --reporter mocha-junit-reporter
          environment:
            MOCHA_FILE: ~/junit/test-results.xml
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

  # test:
  #   docker:
  #     - image: circleci/node:8.9.1
  #   steps:
  #     # working_directory: ~/kinesis-stream-reader/app/server
  #     - run: mkdir ~/junit
  #     - run:
  #         command: mocha test --reporter mocha-junit-reporter
  #         environment:
  #           MOCHA_FILE: ~/junit/test-results.xml
  #         when: always
  #     - store_test_results:
  #         path: ~/junit
  #     - store_artifacts:
  #         path: ~/junit
  #     # steps:
  #     #   - run:
  #     #       name: test
  #     #       command: npm test
